pipeline {
  agent any

  environment {
    IMAGE_NAME     = "trend-app"
    DOCKERHUB_REPO = "sudharsanps115/trend-app"
    DOCKER_CREDS  = "dockerhub-creds"
  }

  stages {

    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          docker build -t $IMAGE_NAME .
        '''
      }
    }

    stage('Login & Push Image to DockerHub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${DOCKER_CREDS}",
          usernameVariable: "DOCKER_USER",
          passwordVariable: "DOCKER_PASS"
        )]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_REPO:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
          kubectl apply --validate=false -f Deployment.yaml
          kubectl apply --validate=false -f Service.yaml
        '''
      }
    }
  }

  post {
    success {
      echo "CI/CD Pipeline completed successfully"
    }
    failure {
      echo "CI/CD Pipeline failed"
    }
  }
}
