pipeline {
  agent any

  environment {
    IMAGE_NAME         = "trend-store"
    DOCKERHUB_REPO     = "karthi271/trend-store"
    DOCKER_CREDS       = "dockerhub-creds"

    AWS_DEFAULT_REGION = "ap-south-1"
    EKS_CLUSTER_NAME   = "trend-cluster"
  }

  stages {

    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
          docker build -t $IMAGE_NAME .
        '''
      }
    }

    stage('Login & Push Image to DockerHub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: DOCKER_CREDS,
          usernameVariable: "DOCKER_USER",
          passwordVariable: "DOCKER_PASS"
        )]) {
          sh '''
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker tag $IMAGE_NAME $DOCKERHUB_REPO:${BUILD_NUMBER}
            docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest
            docker push $DOCKERHUB_REPO:${BUILD_NUMBER}
            docker push $DOCKERHUB_REPO:latest
          '''
        }
      }
    }

    stage('Configure kubeconfig') {
      steps {
        sh '''
          aws eks update-kubeconfig \
            --region $AWS_DEFAULT_REGION \
            --name $EKS_CLUSTER_NAME
        '''
      }
    }

    stage('Deploy to EKS') {
      steps {
        sh '''
          kubectl apply -f Deployment.yaml
          kubectl apply -f Service.yaml
          kubectl rollout status deployment/trend-store
        '''
      }
    }
  }

  post {
    success {
      echo "✅ CI/CD Pipeline completed successfully"
    }
    failure {
      echo "❌ CI/CD Pipeline failed"
    }
  }
}
