pipeline {
    agent any

    environment {
        DEV_IMAGE  = "karthi271/react-app-dev:latest"
        PROD_IMAGE = "karthi271/react-app-prod:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('react') {
                    sh 'docker build -t react-app .'
                }
            }
        }

        stage('Push to DEV Repo') {
            when {
                branch 'dev'
            }
            steps {
                dir('react') {
                    sh """
                        docker tag react-app:latest ${DEV_IMAGE}
                        docker push ${DEV_IMAGE}
                    """
                }
            }
        }

        stage('Push to PROD Repo') {
            when {
                branch 'main'
            }
            steps {
                dir('react') {
                    sh """
                        docker tag react-app:latest ${PROD_IMAGE}
                        docker push ${PROD_IMAGE}
                    """
                }
            }
        }

        stage('Deploy to EC2') {
            when {
                branch 'main'
            }
            steps {
                sh """
                    docker rm -f react-container || true
                    docker run -d \
                      -p 80:80 \
                      --restart always \
                      --name react-container \
                      ${PROD_IMAGE}
                """
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}
