version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - node -v
      - npm -v
      - aws sts get-caller-identity
      - aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin 792557500634.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - npm install
      - npm run build
      - ls -la dist
      - docker build -t brain-task-app .

  post_build:
    commands:
      - docker tag brain-task-app:latest 792557500634.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
      - docker push 792557500634.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app:latest
